# EditableStands: v1.3.1
# Author: lluk

# Editing stands capabilities
# true > enable | false > disable
armsAdd: true
armsRemove: true
plateAdd: true
plateRemove: true
doSmall: true
doBig: true

# Whether to drop items when editing armor stand
dropItems: true

# Whether to play sound when editing armor stand
playSounds: true

# Whether to remove items from the player when editing armor stand
removeItems: true
removeItemsInCreative: false

# Whether to damage items when editing armor stand
damageTools: true
damageToolsInCreative: false